import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "../../context/Provider";
import LayoutWrapper from "./component/layoutwrapper/page";

// const pathname = usePathname();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <LayoutWrapper children={children}></LayoutWrapper>
          {/* <Header />
          {children} */}
        </body>
      </Provider>
    </html>
  );
}
